name: CI
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

env:
  NX_CLOUD_ACCESS_TOKEN: ${{secrets.NX_CLOUD_ACCESS_TOKEN}}

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'yarn'
      - run: yarn install --frozen-lockfile

      - run: npx nx-cloud start-ci-run --distribute-on="5 linux-medium-js" --stop-agents-after="e2e"
      - uses: nrwl/nx-set-shas@v4

      - run: npx nx-cloud record -- nx format:check
      - run: npx nx-cloud record -- nx sync:check

      - run: npx nx run-many -t lint test build
      - run: npx nx run-many -t e2e --exclude=nx-ignore-e2e

      - name: Self-healing
        run: npx nx fix-ci
        if: always()
