name: CI
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

env:
  NX_CLOUD_ACCESS_TOKEN: ${{secrets.NX_CLOUD_ACCESS_TOKEN}}

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          filter: tree:0

      - run: npx nx-cloud start-ci-run --distribute-on="5 linux-large" --stop-agents-after="e2e"

      - name: Setup dev tools with mise
        uses: jdx/mise-action@146a28175021df8ca24f8ee1828cc2a60f980bd5 # v3

      - name: Install dependencies with bun
        run: bun install --frozen-lockfile

      - uses: nrwl/nx-set-shas@v5

      - run: bunx nx-cloud record -- nx format:check
      - run: bunx nx-cloud record -- nx sync:check

      - run: bunx nx run-many -t lint test build
      - run: bunx nx run-many -t e2e --exclude=nx-ignore-e2e

      - name: Self-healing
        run: bunx nx fix-ci
        if: always()
